[postgres]
driver = "postgres"
source = "postgresql://root:root@localhost:5432/blog?sslmode=disable&timeZone=Asia/Shanghai"
migrate_url = "file://db/migration"

[token]
token_symmetric_key = "plokmnjiuhbvgytfcxdreszawq564738"
access_token_duration = "30m"

[server]
address = "0.0.0.0:9010"

[redis]
address = "localhost:6379"
password = ""
db = 0

[oss_qiniu]


[zap]
time_format = 2006-01-02 15:04:05Z
level = "debug"
caller = true
stack_trace = true
writer_file = true

    [zap.log_file]
    max_size = 20
    max_age = 7
    backups = 5
    compress = true
    output = "./log/blog.log"