version: "3.9"
services:

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9010:9010"
    environment:
      GIN_MODE: release
      POSTGRES.SOURCE: postgresql://root:root@postgres:5432/blog?sslmode=disable&timeZone=Asia/Shanghai
    depends_on:
      - postgres
    entrypoint: [
      "/app/wait-for.sh",
      "postgres:5432",
      "--",
      "/app/start.sh"
    ]
    command: ["/app/blog"]