DROP TABLE IF EXISTS blogs;
DROP TABLE IF EXISTS types;

ALTER TABLE IF EXISTS "blogs" DROP CONSTRAINT IF EXISTS "blogs_owner_id_fkey";
ALTER TABLE IF EXISTS "blogs" DROP CONSTRAINT IF EXISTS "blogs_type_id_fkey";