// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	CountArticle(ctx context.Context) (int64, error)
	CreateComment(ctx context.Context, arg *CreateCommentParams) (Comment, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (User, error)
	DeleteArticle(ctx context.Context, id int64) error
	GetArticle(ctx context.Context, id int64) (GetArticleRow, error)
	GetChildComments(ctx context.Context, parentID int64) ([]Comment, error)
	GetComments(ctx context.Context, ownerID int64) ([]Comment, error)
	GetUser(ctx context.Context, username string) (User, error)
	IncrViews(ctx context.Context, id int64) error
	InsertArticle(ctx context.Context, arg *InsertArticleParams) (Blog, error)
	ListArticles(ctx context.Context, arg *ListArticlesParams) ([]ListArticlesRow, error)
	SearchArticle(ctx context.Context, arg *SearchArticleParams) ([]SearchArticleRow, error)
	UpdateArticle(ctx context.Context, arg *UpdateArticleParams) (Blog, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
