// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	CountArticle(ctx context.Context) (int64, error)
	CreateCritique(ctx context.Context, arg *CreateCritiqueParams) (Critique, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (User, error)
	DeleteArticle(ctx context.Context, id int64) error
	GetArticle(ctx context.Context, id int64) (GetArticleRow, error)
	GetChildCritiques(ctx context.Context, parentID int64) ([]Critique, error)
	GetCritiques(ctx context.Context, ownerID int64) ([]Critique, error)
	GetUser(ctx context.Context, username string) (User, error)
	IncrViews(ctx context.Context, id int64) error
	InsertArticle(ctx context.Context, arg *InsertArticleParams) (Article, error)
	ListArticles(ctx context.Context, arg *ListArticlesParams) ([]ListArticlesRow, error)
	UpdateArticle(ctx context.Context, arg *UpdateArticleParams) (Article, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
