// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: request_log.sql

package db

import (
	"context"
)

const insertRequestLog = `-- name: InsertRequestLog :one
INSERT INTO request_logs (
    method, path, status_code, ip, hostname, request_body, response_time, content_type, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, method, path, status_code, ip, hostname, request_body, response_time, request_time, content_type, user_agent
`

type InsertRequestLogParams struct {
	Method       string `json:"method"`
	Path         string `json:"path"`
	StatusCode   int32  `json:"status_code"`
	Ip           string `json:"ip"`
	Hostname     string `json:"hostname"`
	RequestBody  string `json:"request_body"`
	ResponseTime int64  `json:"response_time"`
	ContentType  string `json:"content_type"`
	UserAgent    string `json:"user_agent"`
}

func (q *Queries) InsertRequestLog(ctx context.Context, arg *InsertRequestLogParams) (RequestLog, error) {
	row := q.db.QueryRowContext(ctx, insertRequestLog,
		arg.Method,
		arg.Path,
		arg.StatusCode,
		arg.Ip,
		arg.Hostname,
		arg.RequestBody,
		arg.ResponseTime,
		arg.ContentType,
		arg.UserAgent,
	)
	var i RequestLog
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.Path,
		&i.StatusCode,
		&i.Ip,
		&i.Hostname,
		&i.RequestBody,
		&i.ResponseTime,
		&i.RequestTime,
		&i.ContentType,
		&i.UserAgent,
	)
	return i, err
}
