// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: type.sql

package db

import (
	"context"
)

const insertType = `-- name: InsertType :one
INSERT INTO types (
    type_name
) VALUES (
    $1
)
RETURNING id, type_name
`

func (q *Queries) InsertType(ctx context.Context, typeName string) (Type, error) {
	row := q.db.QueryRowContext(ctx, insertType, typeName)
	var i Type
	err := row.Scan(&i.ID, &i.TypeName)
	return i, err
}
