server:
  port: 6754
  host: localhost

mysql:
  host: 127.0.0.1
  port: 3306
  dbname: blog
  username: root
  password: qianxia
  charset: utf8mb4
  loc: Asia/Shanghai

qiniu:
  access_key: 
  secret_key: 
  bucket: 
  server_url: 