server:
  port: 6754
  host: localhost

mysql:
  host: 127.0.0.1
  port: 3306
  dbname: blog
  username: root
  password: qianxia
  charset: utf8mb4
  loc: Asia/Shanghai

qiniu:
  access_key: vz0iB4SnKnxXAEoxbW6TQvVxrfqOspnhYQzrPL3j
  secret_key: GufJ3mD3z13EFXAaW_Y_PzI4n-uj4_I7ax-Vz6Dr
  bucket: lyy-blog
  server_url: http://r8rvr1zhk.hn-bkt.clouddn.com/