[http]
port = 6754
host = "localhost"

[mysql]
host = "localhost"
port = 3306
dbname = "blog"
username = "root"
password = "qianxia"
charset = "utf8mb4"
loc = "Asia/Shanghai"
# 连接池最大空闲数
max_idle = 8
# 连接池最大连接数
max_open = 20

[redis]
host = "localhost"
port = 6379
db = 0
password = ""

[qiniu]
access_key = ""
secret_key = ""
bucket = ""
server_url = ""

[captcha]
height = 80
width = 240
length = 5
max_skew = 0.8
dot_count = 80

[email]
addr = "smtp.qq.com:587"
username = ""
password = ""
host = "smtp.qq.com"