[http]
port = 6754
host = "localhost"

[mysql]
host = "localhost"
port = 3306
dbname = "blog"
username = "root"
password = "qianxia"
charset = "utf8mb4"
loc = "Asia/Shanghai"
# 连接池最大空闲数
max_idle = 8
# 连接池最大连接数
max_open = 20

[redis]
host = "localhost"
port = 6379
db = 0
password = ""

[qiniu]
access_key = ""
secret_key = ""
bucket = ""
server_url = ""

[captcha]
height = 240
width = 60
noise_count = 75
show_line_options = 4
length = 6
source = "1234567890qwertyuioplkjhgfdsazxcvbnm"
    [captcha.color]
    R = 0
    G = 0
    B = 0
    A = 0
    
